use_frameworks!

platform :ios, '10.0'

target 'MSSerialPort_Example' do
  pod 'MSSerialPort', :path => '../'
  
  pod 'SwiftNIO'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwifterSwift/UIKit'
  pod 'SwifterSwift/Foundation'
  pod 'SwifterSwift/SwiftStdlib'
  pod 'CryptoSwift'
end
